version: '3'
services:
  postgresql:
    image: postgres:10
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduled_payout_worker
